### ISSUE TITLE
[BUG] : Failed to execute 'insertRule' on 'CSSStyleSheet' (Rare, some mobile devices)

### ISSUE THREAD

**Issue by Jervx** [guilhermerodz/input-otp#37]
On some rare cases this error shows on some devices. This was sent to me by my client, She tried it on her husbands phone and the otp works, just on some devices it shows this error. I tried on other mobile devices I have here and couldn't recreate the error.

![image](https://github.com/guilhermerodz/input-otp/assets/48374007/4fd9a918-54b8-4602-ad8e-7bc5696a3e56)

Uppon checking the source code is ``text : transparent`` instead of ```color : transparent```. But I am not sure if this really the cause of the error.

![Screenshot from 2024-03-18 18-54-32](https://github.com/guilhermerodz/input-otp/assets/48374007/516dd606-cb3e-4d54-8a66-ae059eceb398)

Is there a possible fix/workaround for this?

Thanks for response 😄

**Comment by guilhermerodz** [comment]
hi @Jervx you're on point regarding the `text` (should be `color` instead).

just shipped a fix, please run `npm i input-otp@latest`, should be good as of 1.2.1

- what version of input-otp was running when she got the error?

I'm surprised that she was able to read that error as an user, because insertRule is currently happening within a trycatch with console.error as a fallback:

![CleanShot 2024-03-18 at 10 42 22@2x](https://github.com/guilhermerodz/input-otp/assets/10366880/c9a5b6fe-d19f-42de-8ea3-9be0047e3609)

solved by #968a23b

---

just got curious myself @Jervx can you tell me if she was able to use the OTP input besides the error? did the app actually break or is it only an application console log? thanks

**Comment by Jervx** [comment]
Goodmorning,

Appologize I forgot to include the version, I have input-otp 1.0.1 

![image](https://github.com/guilhermerodz/input-otp/assets/48374007/a351e0cb-d32b-4ee9-af91-bcb353bf0020)
About the error, Yes it is breaking the app and only showing a client side exception so I added the ```error.tsx``` to show the error. 


I will update to the latest version and test it again, thank you 😄

**Comment by guilhermerodz** [comment]
hey @Jervx was there any issue while running the latest version?
