### ISSUE TITLE
Masked OTP input

### ISSUE THREAD

**Issue by aiyeola** [guilhermerodz/input-otp#45]
**Is your feature request related to a problem? Please describe.**
For OTP fields that collect sensitive information, like PIN or passcode in financial apps, at this time the package doesn't have an API to mask the entered value

**Describe the solution you'd like**
A boolean value prop called `masked` can be passed to the `InputOTP` component, to either show a masked input or not.

**Comment by guilhermerodz** [comment]
hi @aiyeola thanks for your suggestion!

it seems your feature request does not have enough information on 1. what it does 2. what's the expect developer experience around it and 3. is there any way to implement that with the current library specification, even without a "masked" prop?

from what I understood in your feature request, adding a "mask" functionality is not really needed since you are always able to render whatever character you want to in the UI and have full control of it regardless of the library props, or input type.

**Comment by aiyeola** [comment]
Hi @guilhermerodz you're correct!

yes, the alternative was to render a "masked" character in place of `char`

![image](https://github.com/guilhermerodz/input-otp/assets/47264345/b23aaa64-c1a7-4bff-b44b-6701142241c2)

Thank you for your prompt response.
