### ISSUE TITLE
Support pasting codes as "XXX-XXX"

### ISSUE THREAD

**Issue by necky2** [guilhermerodz/input-otp#53]
**Is your feature request related to a problem? Please describe.**
By my understanding, splitting a code into 2 parts is done for better user readability. This library supports and even suggests, configuring the input as "XXX-XXX". I think it's a problem that a code with a hyphen or space in the middle cannot be pasted into the field.

**Describe the solution you'd like**
Accept pasting of "XXX-XXX" and "XXX XXX" (and possibly other formats)

**Describe alternatives you've considered**
\-

**Additional context**
I can have a shot at implementing this if others agree that this makes sense.

**Comment by guilhermerodz** [comment]
@necky2 thanks for bringing that up. While I still can't think of a great solution for this, there's a workaround such as handling onPaste event.

That would require a change on the current implementation, because it's [always calling the library's default pasteListener](https://github.com/guilhermerodz/input-otp/blob/master/packages/input-otp/src/input.tsx#L420).

If I allow for the user/developer setting up a custom paste event listener over the default library behavior, then it should be possible. I'm also not sure whether or not `input.selectionStart` and `input.selectionEnd` should be managed during this act of pasting a code with a decorative character.

**Comment by buffalom** [comment]
Any update on this? Even just allowing me to reformat the pasted value before the built-in `pasteListener` is called should be sufficient for my use case.

**Comment by necky2** [comment]
> Any update on this? Even just allowing me to reformat the pasted value before the built-in `pasteListener` is called should be sufficient for my use case.

I removed the hyphen from the emails that I send to customers, problem "solved". If you get this issue moving and support is added for this, I would still appreciate that.

**Comment by buffalom** [comment]
> I removed the hyphen from the emails that I send to customers, problem "solved". If you get this issue moving and support is added for this, I would still appreciate that.

In our case, it's not a hyphen in between the code groups, but rather a prefix at the start of the code. Something like `A-12345`. Just to add to the list of use cases.

**Comment by guilhermerodz** [comment]
Hey all @necky2 @buffalom @trm217 @cschmatzler @zfm-andreasmatuszewski

This turned into a new feature as of `1.4.0`:
`<InputOTP pasteTransformer={(pasted) => pasted.replaceAll('-', '')} ...>`

Just upgrade it `npm i input-otp@latest`.

It's also updated in the [docs](https://github.com/guilhermerodz/input-otp?tab=readme-ov-file#props).

**Comment by buffalom** [comment]
Working flawlessly, thank you ❤️
